version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: webpromo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - webpromo_mysql:/var/lib/mysql

  php:
    build:
      context: ./.provision/php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./.provision/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
      - .env.local

  nginx:
    image: nginx:latest
    ports:
      - 83:80
    volumes:
      - .:/var/www/app:cached
      - ./.provision/nginx/docker.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
      - .env.local

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  webpromo_mysql:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
